monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - security

  handlers:
    main:
      type: rotating_file
      level: info
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      max_files: 10
      channels: [ "!deprecation", "!security" ]
    deprecation:
      type: stream
      channels: [ deprecation ]
      path: php://stderr
    security:
      type: rotating_file
      level: info
      path: "%kernel.logs_dir%/%kernel.environment%.security.log"
      max_files: 30
      channels: [ security ]